[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
smartv21 = "H22783urCUvrQSHtwou3x8D3JxxsG8tCiaEdbP9ygsf8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/kartos.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
