[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
smartv21 = "FUBDGjrPeRAXzzxDBhozp6PgiHBPk4gFAYGoab5qZLrp"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "https://devnet.helius-rpc.com/?api-key=44b7171f-7de7-4e68-9d08-eff1ef7529bd"
cluster = "devnet"
wallet = "/root/.config/solana/kartos.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/smartv21.ts"
